### ISSUE TITLE
Tinyfox API

### ISSUE THREAD

**Issue by Deer-Spangle** [FurryBotCo/FoxAPI#3]
Stumbled across your API here, and I ahve another fox API suggestion:
https://tinyfox.dev/img.php?animal=fox
JSON endpoint here: https://tinyfox.dev/img.php?json&animal=fox

Minor notes (and questions) are available from the dev here: https://t.me/FoxesHourlies/68

**Comment by DonovanDMC** [comment]
FurryBotAPI has been transformed into [YiffyAPI](https://yiff.rest), this module is therefore no longer in use.

672102e9ccdcf11c032bdc71b18196af4a75c024
